name: Cart

on:
  push:
    branches:
      - master
    paths:
      - '**.js'  # Only trigger on changes to Python files (**.py)
      - '.github/workflows/cart.yaml'  # Include workflow file changes

  pull_request:
    branches:
      - master
    paths:
      - '**.js'  # Only trigger on changes to Python files (**.py)
      - '.github/workflows/cart.yaml'  # Include workflow file changes

jobs:
  payment:
    name: Build and deploy cart microservice
    runs-on: ubuntu-latest #[self-hosted]  # Use a standard runner instead of self-hosted

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Verify Docker Compose installation
        run: docker-compose --version    

      - name: NPM install dependencies
        run: npm install 

      - name: Build Docker image
        run: |
          docker build -t cart .  # Build image tagged as 'payment' from current directory

      - name: Docker Login (use secrets)
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Push
        run: |
          docker tag cart ${{secrets.DOCKERHUB_USERNAME}}/cart:latest
          docker push ${{secrets.DOCKERHUB_USERNAME}}/cart:latest
