name: Catalogue

on:
  push:
    branches:
      - master
    paths:
      - '**.js'  # Only trigger on changes to Python files (**.py)
      - '.github/workflows/catalogue.yaml'  # Include workflow file changes

  pull_request:
    branches:
      - master
    paths:
      - '**.js'  # Only trigger on changes to Python files (**.py)
      - '.github/workflows/catalogue.yaml'  # Include workflow file changes

jobs:
  payment:
    name: Build and deploy catalogue microservice
    runs-on: ubuntu-latest #[self-hosted]  # Use a standard runner instead of self-hosted

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Verify Docker and Docker Compose installation
        run: |
          docker --version
          docker-compose --version
          
      - name: NPM install
        run:  |
          cd catalogue 
          npm install 

      - name: Build Docker image
        run: |
          cd catalogue
          docker build -t catalogue .  # Build image tagged as 'payment' from current directory

      - name: Docker Login (use secrets)
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Push
        run: |
          docker tag catalogue ${{ secrets.DOCKERHUB_USERNAME }}/catalogue:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/catalogue:latest
